---
- name: setup directories                                                      
  file: path=~/{{ item.path }} owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }} mode=0755 state=directory
  with_items:                                                                  
    - { path: '.vimswap' }                                                     
    - { path: '.vimbackup' }                                                   
    - { path: '.vim' }                                                         
    - { path: '.vim/colors' }                                                  
    - { path: '.vim/bundle' }                                                  
    - { path: 'dev' }                                                          
                                                                               
- name: setup files                                                            
  copy: src={{ item.name }} dest=~/{{ item.name }} owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }} force=yes
  with_items:                                                                  
    - { name: '.tmux.conf' }                                                   
    - { name: '.gitconfig' }                                                   
    - { name: '.bashjm' }                                                      
    - { name: '.vimrc' }                                                      
    - { name: '.eslintrc' }                                                      
    - { name: '.powconfig' }                                                      
